### ISSUE TITLE
Error in Terminal

### ISSUE THREAD

**Issue by Unknown303YT** [chapnickc/WizHook#2]
Hi @larochefoucald!
After running these commands*, I occasionaly get this error:
`ERROR:root:0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.spotify.com/v1/me/player/currently-playing')
Traceback (most recent call last):
  File "/home/[user]/Downloads/WizHook-main/app/SpotifyChangeListener.py", line 66, in listen
    async for event in self._listen_for_events(session):
  File "/home/[user]/Downloads/WizHook-main/app/SpotifyChangeListener.py", line 48, in _listen_for_events
    current = await self._get_current_playing(session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/Downloads/WizHook-main/app/SpotifyChangeListener.py", line 34, in _get_current_playing
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/.local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api.spotify.com/v1/me/player/currently-playing')
`
Afterwards, the program keeps running, and I'm not sure why. Could someone please help?

Thanks,
Aidan R

*`. ./env.sh` & `python3 main.py`

**Comment by smartsousa** [comment]
Hi friend...after run Terminal this happens to me 

ERROR:root:Cannot connect to host api.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedrosousa/WizHook/app/SpotifyChangeListener.py", line 66, in listen
    async for event in self._listen_for_events(session):
  File "/Users/pedrosousa/WizHook/app/SpotifyChangeListener.py", line 48, in _listen_for_events
    current = await self._get_current_playing(session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pedrosousa/WizHook/app/SpotifyChangeListener.py", line 33, in _get_current_playing
    async with session.get(config.API_CURRENT_PLAYING) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.spotify.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]


Can you help me?

**Comment by chapnickc** [comment]
Hi there, this looks like an issue with the request to the Spotify API. Just tested the latest main branch with python3.11--that does not seem to be the issue. Could be environment specific. There is a step in the README about 

> The first time you run the script you need to obtain credentials. The workflow for this is a little funky. Running main.py should start your browser and redirect you to a URL. Copy and paste the url from the browser into Terminal.app.

Double checking this step may be helpful. Another item is to try to pin the set of libraries you are using by creating a [virtual environment](https://docs.python.org/3/library/venv.html) for your project.

This is not related to the original issue, so feel free to create a new one.

**Comment by Unknown303YT** [comment]
I tried that, but I still get this error:
`ERROR:root:204, message='Attempt to decode JSON with unexpected mimetype: ', url='https://api.spotify.com/v1/me/player/currently-playing'
Traceback (most recent call last):
  File "/home/cottage-admin/WizHook/app/SpotifyChangeListener.py", line 66, in listen
    async for event in self._listen_for_events(session):
  File "/home/cottage-admin/WizHook/app/SpotifyChangeListener.py", line 48, in _listen_for_events
    current = await self._get_current_playing(session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottage-admin/WizHook/app/SpotifyChangeListener.py", line 34, in _get_current_playing
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cottage-admin/WizHook/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1281, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 204, message='Attempt to decode JSON with unexpected mimetype: ', url='https://api.spotify.com/v1/me/player/currently-playing'`

This is using python 3.12 on Ubuntu 24.04 LTS with a .venv enabled, only modules installed are aiohttp, spotipy and pywizlight.

**Comment by chapnickc** [comment]
There is a section from the README that should help get past this error
> The first time you run the script you need to obtain credentials. The workflow for this is a little funky. Running main.py should start your browser and redirect you to a URL.
>
> Copy and paste the url from the browser into Terminal.app.

That said, it appears Spotify has unfortunately disabled this Audio Analysis API, effectively breaking this integration.
> Effective today, new Web API use cases will no longer be able to access or use the following endpoints:
> [...] 
>  [Audio Analysis](https://developer.spotify.com/documentation/web-api/reference/get-audio-analysis) 
> 
> These changes will impact the following Web API applications:
> Existing apps that are still in development mode without a pending extension request

https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

Can confirm this as I'm receiving 403 status codes
```
 curl --request GET \
  --url https://api.spotify.com/v1/audio-analysis/11dFghVXANMlKmJXsNCbNl \
  --header 'Authorization: Bearer ...'
  
  {"error":{"status": 403}}
```

The pywizlight api continues to function, and there may be other avenues to explore for audio-based lighting effects.

**Comment by Unknown303YT** [comment]
Question, what part of the code handles the audio analysis?
This is so if I find another way I can implement it.

**Comment by chapnickc** [comment]
The basic idea is that as the audio plays, we determine a color for the current time, then send that to the light. There was an attempt to encapsulate this color determination  in `AnalysisHelper`.  

The codebase uses asyncio's event loop to achieve some parallelism, which adds a bit of complexity and indirection. Nonetheless, the general flow is 
- `SpotifyChangeListener` would "listen" to the current song and query the audio analysis api for features at current time (beat, pitch, timbre, etc). 
-  `EventSongChanged` is put onto the event loop and contains the audio features at the current time.
- `LightController` then consumes that event and finds the relevant color to send by asking the  the `AnalysisHelper`.

With the help of something like [`librosa`](https://librosa.org/doc/latest/advanced.html) it might be possible to conduct relatively trivial analysis (such as beat detection, chroma features) and yield satisfying results when interfacing with the light. Certainly when you have the entire audio file present up-front, and possibly with real-time streaming too. 


https://librosa.org/doc/latest/advanced.html




https://en.wikipedia.org/wiki/Chroma_feature


For a very basic example of using the Wiz api
```py
import asyncio
from pywizlight.bulb import wizlight, PilotBuilder

the_ip = '1.2.3.4'

async def example():
    light = wizlight(the_ip)
    await light.turn_on(PilotBuilder(rgb=(255, 0, 0)))

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(example())
```

Where `the_ip` was determined from:
```sh
$ wizlight discover
Set the broadcast address: 192.168.0.255
Search for bulbs in 192.168.0.255 ...
{'ip_address': <the_ip>, 'mac_address': '...'}
```
